import type { Metadata } from "next";
import { Suspense } from "react";
import "./globals.css";
import Navbar from "@/sections/navbar/Navbar";
import Footer from "@/sections/footer/Footer";
import LayoutFallBack from "@/components/FallBack/LayoutFallback";

export const metadata: Metadata = {
  title: "Landingvault",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-Switzer antialiased`}>
        <Navbar />
        <div className="mt-[60px]">
          {/* Wrap children in Suspense for fallback */}
          <Suspense fallback={<LayoutFallBack />}>
            {children}
          </Suspense>
        </div>
        <Footer />
      </body>
    </html>
  );
}
